schema_version: 1

context:
  name: pytango-db
  version: "0.9.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pytango_db-${{ version }}.tar.gz
  sha256: d9efbe659aef425bd888e1202585d8618646ae623f8cef8197ee69d7d25f352e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - PyDatabaseds = databaseds.database:main
      - pytango-db-migrate-sqlite = databaseds.migrate:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - pytango

tests:
  - python:
      imports:
        - databaseds
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*
  - script:
      - PyDatabaseds --help
      - pytango-db-migrate-sqlite --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Fork of PyTango's internal sqlite based database device.
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  homepage: https://gitlab.com/tango-controls/incubator/pytango-db
  repository: https://gitlab.com/tango-controls/incubator/pytango-db

extra:
  recipe-maintainers:
    - beenje
